#!/usr/bin/env python3
# XLSX_Cleaner_V2
# Weston Spiro 2023
import tkinter as tk
from tkinter import filedialog, messagebox
import pandas as pd

def clean_file(input_file):
    output_file = input_file[:-5] + "Cleaned.xlsx"
    df = pd.read_excel(input_file)
    df = df.applymap(lambda x: ''.join([i for i in str(x) if i.isalnum() or i in [' ', '-']]))
    df.to_excel(output_file, index=False)
    return output_file

def browse_file():
    file_path = filedialog.askopenfilename()
    if file_path:
        cleaned_file = clean_file(file_path)
        file_name = file_path.split("/")[-1]
        messagebox.showinfo(title="Success", message=f"{file_name} \ncleaned successfully \nand saved as \n{cleaned_file}")

root = tk.Tk()
root.title("The_XLSX_Cleaner")

browse_button = tk.Button(root, text="Select XLSX file", command=browse_file)
browse_button.pack()

quit_button = tk.Button(root, text="Quit", command=root.destroy)
quit_button.pack()

label_text = "The XLSX Cleaner \n Weston Spiro 2023"
label = tk.Label(root, text=label_text)
label.pack()

root.mainloop()
